### PR TITLE
Expected output

### PR DESCRIPTION
**Pull request by lochel**

### CODE REVIEW

**Comment by lochel** [comment]
@robbr48 Not sure how to fix this test case. `getReal` is failing for 4 signals.

**Comment by robbr48** [comment]
@lochel That's weird. The FMUs are handcoded and have no error handling in the setReal function. Hence, they should always return success even if variable name does not exist. Do you know for which variables it failed?

**Comment by lochel** [comment]
getReal is called for some system connectors that do not exist - I think. It is not about the FMUs.

**Comment by lochel** [comment]
```bash
> OMSimulator tlm1dfg.lua && grep error tlm1dfg.log
Starting TLM simulation.
Monitoring thread finished.
Manager thread finished.
wc1.P.v [m/s] is equal
wc2.P.v [m/s] is equal
wc1.P.F [N] is equal
wc2.P.F [N] is equal
info:    Logging information has been saved to "tlm1dfg.log"
info:    0 warnings
info:    4 errors
Thu Jan 24 10:20:43 2019 | error:   [getReal] Unknown signal "model.tlm1dfg.wc2.wave1"
Thu Jan 24 10:20:43 2019 | error:   [getReal] Unknown signal "model.tlm1dfg.wc2.velocity"
Thu Jan 24 10:20:43 2019 | error:   [getReal] Unknown signal "model.tlm1dfg.wc1.wave1"
Thu Jan 24 10:20:43 2019 | error:   [getReal] Unknown signal "model.tlm1dfg.wc1.velocity"
```

**Comment by robbr48** [comment]
Ok, it's an internal call to getReal. But it makes no sense. Both FMUs have both the "wave1" and the "velocity" signal. I need to have a closer look myself.

**Pull request closed without merging**
